#!/usr/bin/env python3
"""Generate the B5 axisymmetric cell and four transparent flux stations.

Dimensions: 38.1 mm body ID, 63.5 mm body length, 5 mm aperture diameter,
1.5 mm plate thickness, 1.65 mm feed-bore ID, and 5 mm simulated feed stub.
The inlet cap is a reflecting 4 K surface with prescribed mass injection.
Closed solid loops run clockwise so line normals face the gas. Stations
extend through walls and avoid grid faces at the local refinement levels.
Keep these coordinates consistent with in.he_b5_mflow when changing geometry.

Run from the repository root: python cases/b5-lean/gen_b5.py
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))

DX = 4.0e-4                 # base axial cell (deck: create_grid 244 50 1 over 0.0976 x 0.0195)
DR = 0.0195 / 50            # base radial cell, 0.39 mm (the deliberate 0.39 offset)
XLO = -0.005
RB = 0.825e-3               # real bore radius
RCELL = 0.01905
XPLATE = 0.0635             # plate cell-side face
XEXIT = 0.0650              # channel exit (1.5 mm plate)
RAP = 0.0025
XC = XLO + 1.5 * DX / 16    # cap: mid-cell at L5 (25 um), 37.5 um inside xlo
XTUBE = -0.001975           # tube station, mid-cell at L4 (50 um)
XAP = 0.064225              # aperture station, mid-cell at L3 (100 um)
R_TUBE_ST = 0.0011          # through the bore wall into solid
R_AP_ST = 0.0038            # through the channel wall into the plate
XOUT, ROUT, RTOP = -0.0053, -0.0003, 0.021

def nonface(name, coord, origin, base, finest_level):
    """Assert coord is not on a cell face at levels 1..finest_level of a 2x hierarchy."""
    for lev in range(1, finest_level + 1):
        h = base / 2 ** (lev - 1)
        idx = (coord - origin) / h
        assert abs(idx - round(idx)) > 1e-6, "%s on a cell face at L%d (index %.4f)" % (name, lev, idx)
    print("%-8s %.7g  non-face down to L%d (%.3g um)" % (name, coord, finest_level, base / 2 ** (finest_level - 1) * 1e6))


def station(x, rtop, tag, fwd):
    p = [(x, 0.0), (x, rtop)] if fwd else [(x, rtop), (x, 0.0)]
    hdr = "# GENERATED by gen_b5.py. %s station at x = %.7g, %s movers (p1->p2 %s)." % (
        tag, x, "+x" if fwd else "-x", "+r" if fwd else "-r")
    return "\n".join([hdr, "", "2 points", "1 lines", "", "Points", "",
                      "1 %.9g %.9g" % p[0], "2 %.9g %.9g" % p[1], "", "Lines", "", "1 1 2", ""])


def loop():
    pts = [(XEXIT, RTOP), (XEXIT, RAP), (XPLATE, RAP), (XPLATE, RCELL), (0.0, RCELL),
           (0.0, RB), (XC, RB), (XC, ROUT), (XOUT, ROUT), (XOUT, RTOP)]
    types = [1, 1, 1, 1, 1, 1, 2, 1, 1, 1]
    n = len(pts)
    out = ["# GENERATED by gen_b5.py -- B5 hardware cell, 2D axisymmetric, emitting cap inlet.",
           "# 38.1 x 63.5 mm body, 5 mm aperture through 1.5 mm plate (0.0635-0.0650),",
           "# real bore r %.6g, 5 mm stub, CAP (type 2) at x = %.7g, normal +x." % (RB, XC),
           "# type 1 = every wall; read with `type group cellwalls clip`, then `group cap surf type 2`.",
           "", "%d points" % n, "%d lines" % n, "", "Points", ""]
    out += ["%d %.9g %.9g" % (i + 1, x, y) for i, (x, y) in enumerate(pts)]
    out += ["", "Lines", ""]
    out += ["%d %d %d %d" % (i + 1, types[i], i + 1, (i + 1) % n + 1) for i in range(n)]
    out.append("")
    return "\n".join(out)


def main():
    nonface("cap x", XC, XLO, DX, 5)
    nonface("bore r", RB, 0.0, DR, 5)
    nonface("tube st", XTUBE, XLO, DX, 4)
    nonface("ap st", XAP, XLO, DX, 3)
    nonface("r_cell", RCELL, 0.0, DR, 1)
    nonface("r_ap", RAP, 0.0, DR, 3)
    for name, text in {
        "cell_b5.surf": loop(),
        "tube_fwd.surf": station(XTUBE, R_TUBE_ST, "tube", True),
        "tube_rev.surf": station(XTUBE, R_TUBE_ST, "tube", False),
        "ap_fwd.surf": station(XAP, R_AP_ST, "aperture", True),
        "ap_rev.surf": station(XAP, R_AP_ST, "aperture", False),
    }.items():
        with open(os.path.join(HERE, name), "w", newline="\n") as f:
            f.write(text)
        print("wrote", name)
    sccm = 4.0
    ndot = sccm * 4.478e17
    mdot = ndot * 6.6464791e-27
    fill = 4 * ndot / (1.07 * 145.5 * 3.141592653589793 * RAP ** 2)
    print("4 SCCM: Mdot = %.6e kg/s, aperture-law fill n = %.4e m^-3" % (mdot, fill))


if __name__ == "__main__":
    main()
